# Generated by Django 6.0.1 on 2026-01-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
